#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook: lint-staged..."
npx lint-staged --quiet
# If lint-staged exits with an error (e.g., linter errors), it will prevent the commit.
